(procedureConfig
  (desmosEntryPoint main)
  (pointerStack ps)
  (programCounter pc)
)

(= i 0)
(= j 0)
(= z 0)
(= a 1)
(procedure test
  (-> a (+ a 1))
  (-> z (+ z 1))
  (if (> 3 z)
    (callprocedure test)
  )  
)
(procedure main
  (while (> 5 i) 
    (if (> i 1)
      (-> a (+ a 1000))
    )
    (-> a (+ a 1))
    (-> a (+ a 4))
    (-> j 0)
    (while (> 3 j)
      (-> a (- a 10))
      (-> j (+ j 1))
    )
    (-> a (- a 6))
    (-> j 0)
    (while (> 3 j)
      (-> a (+ a 10))
      (-> j (+ j 1))
    )
    (-> z 0)
    (callprocedure test)
    (-> i (+ i 1))
  )
)